### ISSUE TITLE
Infer phpdoc return type based on shape

### ISSUE THREAD

**Issue by simPod** [php-standard-library/phpstan-extension#15]
I wonder if there's any way to infer a type for phpdoc from `shape()`.

I often define a complex type using `shape()`. Then I want to put it into a method to allow it's reuse.  
However, there's no way to somehow make phpstan infer the method's return type so you have to redefine the shape again in your `@return` phpdoc.

```php
/**
 * @return IHaveToWriteThisComplexShapeAgainForPhpdocWhichIsVeryTedious
 */
function coerce(mixed $v): array {
   return shape(...)->coerce($v);
}
```

Any ideas how this could be improved?

**Comment by ondrejmirtes** [comment]
> Any ideas how this could be improved?

It can't without making PHPStan much slower.

Your best option is to repeat the array shape in `@return` as you're doing now.

You could also write a custom script (with the help of custom PHPStan collectors) that would sync the PHPDoc array shape with the actually returned array shape by your function.

**Comment by simPod** [comment]
Aight, thanks for input.
