### ISSUE TITLE
support `Psl\invariant`

### ISSUE THREAD

**Issue by bendavies** [php-standard-library/phpstan-extension#4]
Hi, 

Until phpstan has its own `assert`/type narrowing support:
 - https://github.com/phpstan/phpstan/issues/7110
 - https://github.com/phpstan/phpstan-src/pull/1317

it would be good to have support for
`\Psl\Invariant` (https://github.com/azjezz/psl/blob/2.1.x/src/Psl/invariant.php#L12) in this extension.

example:
doesn't work:
```php
\PHPStan\dumpType($result); //$result = Divsion|null

Psl\invariant(
    null !== $result,
    Str\format('Division with ID %s not found', $uuid->toRfc4122()),
);

\PHPStan\dumpType($result); //$result = Divsion|null
```

Thanks

**Comment by azjezz** [comment]
unrelated, but you don't have to use str\format with invariant, the message will be formatted with additional arguments internally using str\format :D

**Comment by bendavies** [comment]
ah, thanks!

**Comment by BackEndTea** [comment]
I think this will be supported without the need for this extension, once phpstan supports '@assert' annotations

**Comment by ondrejmirtes** [comment]
Can you please test `phpstan/phpstan` `1.9.x-dev`?

**Comment by bendavies** [comment]
@ondrejmirtes doesn't work i'm afraid. which commit in 1.9 do you think fixes this?

```sh
composer req phpstan/phpstan:1.9.x-dev
./composer.json has been updated
Running composer update phpstan/phpstan
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading phpstan/phpstan (1.8.11 => 1.9.x-dev 698f3cc)
```
Added a testcase here:
```php
<?php declare(strict_types=1);

namespace PslShapeTest;

use function PHPStan\Testing\assertType;
use Psl;

class AssertTest
{
	/**
	 * @param null|array<mixed> $a
	 */
	public function assertNotNull(?array $a): void
	{
		Psl\invariant(
			null !== $a,
			'$a is null.',
		);

		assertType('array<mixed>', $a);
	}
}

```

```sh
Expected type array<mixed>, got type array|null in/phpstan-extension/tests/Type/data/invariant.php on line 22.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'array<mixed>'
+'array|null'
```

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-src/pull/1957
